<a href="https://colab.research.google.com/github/veniapputrii/Python/blob/Projects/Python_ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#15. Feb
import pandas as pd
#Tabelle 1. Die Mitarbeiter
daten_m = {
    'Name' : ['Anna', 'Ben', 'Clara', 'David'],
    'Team_Code' : [1,2,1,3] #Das ist der Schlüssel
}

df_mitarbeitr = pd.DataFrame(daten_m)

#Tabelle 2 : Die Team-Namen
daten_t = {
    'ID' : [1,2,3],
    'Team_Name' : ['IT', 'Sales', 'HR'] #Die Übersetzung für den Code
}

df_teams = pd.DataFrame(daten_t)

print("___Tabelle 1: Mitarbeiter ___")
display(df_mitarbeitr)
print("___Tabelle 2: Teams ___")
display(df_teams)

___Tabelle 1: Mitarbeiter ___

    Name  Team_Code
0   Anna          1
1    Ben          2
2  Clara          1
3  David          3

___Tabelle 2: Teams ___

   ID Team_Name
0   1        IT
1   2     Sales
2   3        HR

In [ ]:
# 16.Feb
df_komplett = pd.merge(
    df_mitarbeitr,
    df_teams,
    left_on = 'Team_Code',
    right_on= 'ID'
)

display(df_komplett)

    Name  Team_Code  ID Team_Name
0   Anna          1   1        IT
1    Ben          2   2     Sales
2  Clara          1   1        IT
3  David          3   3        HR

In [ ]:
#17. Feb
daten_m = 7{
    'Name' : ['Anna','Ben','Clara','David'],
    'Team_Code' : [1,2,1,3,99]
}
df_mitarbeiter_neu ≠ pd.DataFrame(daten_m)

SyntaxError: invalid character '≠' (U+2260) (ipython-input-2191419728.py, line 6)