<a href="https://colab.research.google.com/github/veniapputrii/Python/blob/Projects/Python_ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#15. Feb
import pandas as pd
#Tabelle 1. Die Mitarbeiter
daten_m = {
    'Name' : ['Anna', 'Ben', 'Clara', 'David'],
    'Team_Code' : [1,2,1,3] #Das ist der Schlüssel
}

df_mitarbeitr = pd.DataFrame(daten_m)

#Tabelle 2 : Die Team-Namen
daten_t = {
    'ID' : [1,2,3],
    'Team_Name' : ['IT', 'Sales', 'HR'] #Die Übersetzung für den Code
}

df_teams = pd.DataFrame(daten_t)

print("___Tabelle 1: Mitarbeiter ___")
display(df_mitarbeitr)
print("___Tabelle 2: Teams ___")
display(df_teams)

___Tabelle 1: Mitarbeiter ___

    Name  Team_Code
0   Anna          1
1    Ben          2
2  Clara          1
3  David          3

___Tabelle 2: Teams ___

   ID Team_Name
0   1        IT
1   2     Sales
2   3        HR

In [ ]:
# 16.Feb
df_komplett = pd.merge(
    df_mitarbeitr,
    df_teams,
    left_on = 'Team_Code',
    right_on= 'ID'
)

display(df_komplett)

    Name  Team_Code  ID Team_Name
0   Anna          1   1        IT
1    Ben          2   2     Sales
2  Clara          1   1        IT
3  David          3   3        HR

In [ ]:
#17. Feb
daten_m = {
    'Name' : ['Anna','Ben','Clara','David', 'Emil'],
    'Team_Code' : [1,2,1,3,99],
    'Stadt' : ['Berlin', 'Hamburg', 'München', 'Berlin', 'Frankfurt'],
    'ID'  : [1,2,3,4,5]
}
df_mitarbeiter_neu = pd.DataFrame(daten_m)
print(df_mitarbeiter_neu)

    Name  Team_Code      Stadt  ID
0   Anna          1     Berlin   1
1    Ben          2    Hamburg   2
2  Clara          1    München   3
3  David          3     Berlin   4
4   Emil         99  Frankfurt   5

In [ ]:
#19. Feb. 2026
#Ich will ganz bestimmte Daten daraus filtern

df_komplett2 = pd.merge(
    df_komplett,
    df_mitarbeiter_neu,
    left_on = 'Team_Code',
    right_on = 'ID'
)

display(df_komplett2)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y    Stadt  ID_y
0   Anna            1     1        IT   Anna            1   Berlin     1
1    Ben            2     2     Sales    Ben            2  Hamburg     2
2  Clara            1     1        IT   Anna            1   Berlin     1
3  David            3     3        HR  Clara            1  München     3

In [11]:
#20. Feb. 2026
#Ich zeige euch alle Kunden aus Berlin
filter_Stadt = df_komplett2['Stadt'] == 'Berlin'

Berliner = df_komplett2[filter_Stadt]
display(Berliner)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y   Stadt  ID_y
0   Anna            1     1        IT   Anna            1  Berlin     1
2  Clara            1     1        IT   Anna            1  Berlin     1

In [14]:
#UNd zeige euch alle Mitarbeiter aus Team '1'
filter_Team = df_komplett2['Team_Code_x'] == 1

Ersteteam = df_komplett2[filter_Team]
display(Ersteteam)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y   Stadt  ID_y
0   Anna            1     1        IT   Anna            1  Berlin     1
2  Clara            1     1        IT   Anna            1  Berlin     1

In [17]:
id = df_komplett2[df_komplett2['ID_x'] == 1]
display(id)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y   Stadt  ID_y
0   Anna            1     1        IT   Anna            1  Berlin     1
2  Clara            1     1        IT   Anna            1  Berlin     1